[package]
name = "criu"
version = "0.1.0"
authors = ["Furisto <24721048+Furisto@users.noreply.github.com>"]
edition = "2018"


[dependencies]
bytes = "1"
prost = "0.8"
prost-types = "0.8"
nix = "0.22.0"
anyhow = "1.0"
libc = "0.2"

[build-dependencies]
prost-build = { version = "0.8" }
